<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Farm Details - {{ $record->name }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .details {
            margin-bottom: 30px;
        }

        .section {
            margin-bottom: 20px;
        }

        .section h2 {
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
            font-size: 16px;
        }

        .info-grid {
            display: grid;
            grid-template-columns: 200px 1fr;
            gap: 10px;
            margin-top: 10px;
        }

        .label {
            font-weight: bold;
        }

        .footer {
            margin-top: 50px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Farm Details</h1>
        <p>Generated on: {{ now()->format('F j, Y h:i A') }}</p>
    </div>

    <div class="details">
        <div class="section">
            <h2>Basic Information</h2>
            <div class="info-grid">
                <div class="label">Farm Name:</div>
                <div>{{ $record->name }}</div>

                <div class="label">Location:</div>
                <div>{{ $record->location ?? 'N/A' }}</div>

                <div class="label">Size (hectares):</div>
                <div>{{ $record->size ?? 'N/A' }}</div>

                <div class="label">Established Date:</div>
                <div>
                    {{ $record->established_date ? \Carbon\Carbon::parse($record->established_date)->format('F j, Y') : 'N/A' }}
                </div>
            </div>
        </div>

        @if ($record->description)
            <div class="section">
                <h2>Description</h2>
                <p>{{ $record->description }}</p>
            </div>
        @endif

        @if ($record->users->count() > 0)
            <div class="section">
                <h2>Associated Farmers</h2>
                <ul>
                    @foreach ($record->users as $user)
                        <li>{{ $user->name }} ({{ $user->email }})</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <div class="footer">
        <p>Generated by Agriculture System</p>
    </div>
</body>

</html>
